### ISSUE TITLE
能否用来装ubuntu呢？不想安装windows

### ISSUE THREAD

**Issue by williamnie** [edk2-porting/edk2-sdm845#101]
能否支持装linux系统呢，用来当server。windows没有太大的用途

**Comment by Idonotkno** [comment]
@williamnie 无论有没有uefi，你都可以启动Linux。
Linux你需要自己编译内核，手动配置dts，并手动安装镜像。

**Comment by williamnie** [comment]
> @williamnie 无论有没有uefi，你都可以启动Linux。 Linux你需要自己编译内核，手动配置dts，并手动安装镜像。

大多数教程都是在安卓的基础上输入一个终端，原生linux如何刷入呢？ 我找到一篇通过uefi输入的教程https://forum.renegade-project.cn/t/uefi-ubuntu/605

**Comment by Idonotkno** [comment]
@williamnie 是的，这篇教程尽管麻烦，但是足够参考使用

**Comment by williamnie** [comment]
> @williamnie 是的，这篇教程尽管麻烦，但是足够参考使用

你说的，手动编译内核，配置dts，有参考资料么？我理解安卓就是建立在linux之上的，应该刷入linux不会太麻烦

**Comment by Idonotkno** [comment]
@williamnie 亲呢，根据你的理解程度，对可行性进行了判断，这边建议您呢，早日放弃。

**Comment by williamnie** [comment]
> dts
🤣   还是老老实实树莓派比较好

**Comment by Idonotkno** [comment]
@williamnie kernel.org

**Comment by Idonotkno** [comment]
@williamnie 诶不对，你当server和装Linux有个p关系啊？
你chroot跑一个不就完了。
