### ISSUE TITLE
xiaomi 8 issue Retrofit

### ISSUE THREAD

**Issue by wOscan** [edk2-porting/edk2-sdm845#106]
hey,I have Retrofited my xiaomi 8 and i got a configure that is 10+256.
So,when i use your boot file,i got a blue screen and windows got some information to collect.

**Comment by BigfootACA** [comment]
what is the blue screen code?

**Comment by cander0815** [comment]
我安装了最新版本的镜像后，启动一直出现这个界面。
![Uploading 4759A066-CE22-4C2A-8522-DF3C149ED69C.jpeg…]()

**Comment by cander0815** [comment]
您好，我安装了最新版本的镜像后，启动一直出现这个界面。
![3D207FBA-60D6-481D-89EC-FEF84F57CB2A](https://user-images.githubusercontent.com/23468736/160644443-fa88bc13-4320-456f-a45f-2be7f86d40ce.jpeg)

**Comment by Nigth01F0x** [comment]
Were you able to fix the problem?
once when I installed Windows 10 everything worked, but after reinstalling the blue screen

**Comment by Nigth01F0x** [comment]
> 您好，我安装了最新版本的镜像后，启动一直出现这个界面。 ![3D207FBA-60D6-481D-89EC-FEF84F57CB2A](https://user-images.githubusercontent.com/23468736/160644443-fa88bc13-4320-456f-a45f-2be7f86d40ce.jpeg)

Were you able to fix the problem?
once when I installed Windows 10 everything worked, but after reinstalling the blue screen
