### ISSUE TITLE
小米8安装win11蓝屏

### ISSUE THREAD

**Issue by erge6521** [edk2-porting/edk2-sdm845#110]
设备：小米8普通版本（即非屏下指纹版）
uefi以及驱动版本：目前官网最新以及github上最新的都试过了，都会在安装系统过后蓝屏
win11版本：以前安装成功的镜像以及目前最新的官网镜像都试用过
问题描述：释放完镜像重启开机蓝屏，无法进入系统

**Comment by ShallowAi** [comment]
请问您是否忘记禁用驱动签名验证了

**Comment by erge6521** [comment]
> 请问您是否忘记禁用驱动签名验证了

并没有，我在系统释放以及添加驱动后进行了签名禁用。我以前在刚有手机卡流量能用的版本安装成功过

**Comment by ShallowAi** [comment]
报错是否为 SOC_SUBSYSTEM_ERROR

如果是，可以尝试下载最新的镜像22000.556并重新安装

或预先不释放LTE蓝牙和WIFI驱动。

**Comment by strongtz** [comment]
@erge6521 小米8最新的uefi需要刷写devcfg

**Comment by erge6521** [comment]
> 报错是否为 SOC_SUBSYSTEM_ERROR
> 
> 如果是，可以尝试下载最新的镜像22000.556并重新安装
> 
> 或预先不释放LTE蓝牙和WIFI驱动。

好的，非常感谢您的回复

**Comment by erge6521** [comment]
> @erge6521 小米8最新的uefi需要刷写devcfg

请问具体怎么操作呢

**Comment by strongtz** [comment]
@erge6521 阅读下方的第5点
https://renegade-project.org/#/zh/windows/state-frame.html

**Comment by erge6521** [comment]
> devcfg

非常感谢您，我已经找到了
