### ISSUE TITLE
Pueden ayudarme una imagen de arranque UEFI compatible con mi RED MAGIC 5S

### ISSUE THREAD

**Issue by CHOBITS2022** [edk2-porting/edk2-sdm845#112]
Necesitamos una imagen de arranque UEFI compatible con nuestro modelo de teléfono : RED MAGIC 5S 

EL MODELO DEL DISPOSITIVO ES EL SIGUIENTE: NX659J

**Comment by BigfootACA** [comment]
this repo only accepts sdm845
