### ISSUE TITLE
Poco F1 Win10 not charging

### ISSUE THREAD

**Issue by ClouDROID-Dev** [edk2-porting/edk2-sdm845#116]
My charger is actually working its charge when Android OS is Boot but if i charge on Windows OS is not charging 

how to fix it

**Comment by BigfootACA** [comment]
Duplicate of #107 #86

**Comment by ClouDROID-Dev** [comment]
> Duplicate of #86

I have the default charger but is not charging either my charger is working

**Comment by ClouDROID-Dev** [comment]
> > Duplicate of #86
> 
> I have the default charger but is not charging either my charger is working

can you open my issue again?
Windows OS is newly installed and have a defaul charger but still not charging
