### ISSUE TITLE
Windows ARM Not charging

### ISSUE THREAD

**Issue by ClouDROID-Dev** [edk2-porting/edk2-sdm845#117]
Windows OS is newly installed and have a default charger but still not charging even battery saver not showing

Device : POCO F1
My charger details : 
input 100-240v-50/60hz
output 5v==2a

Maybe causing a problem:
Drivers
Outdated WindowsARM OS

**Comment by Aro2142** [comment]
The smartphone will be charged only from power supplies supporting QC 3.0 and higher!! or use the docking station.

**Comment by ClouDROID-Dev** [comment]
> The smartphone will be charged only from power supplies supporting QC 3.0 and higher!! or use the docking station.

What you mean for this sir

**Comment by Aro2142** [comment]
https://en.m.wikipedia.org/wiki/Quick_Charge

**Comment by ClouDROID-Dev** [comment]
So it will charge if i change the adaptor with that ?

**Comment by ClouDROID-Dev** [comment]
> https://en.m.wikipedia.org/wiki/Quick_Charge ![92026](https://user-images.githubusercontent.com/48096137/162567307-87cac9e5-2bb5-4f2c-a20a-e70a5cef09e7.png)

I used the orginal charger that you suggest but same problem is not charging on windows boot

**Comment by Aro2142** [comment]
Your wire may not have a +/- data line.  
Check the connector, it may be damaged or dirty.
Charging works fine on my poco f1, but sometimes it may not work on the first try.

**Comment by ClouDROID-Dev** [comment]
> 

Its charging on android boot but on windows is not i used dual boot on my poco F1

**Comment by strongtz** [comment]
Use PD chargers instead of QC ones. The driver doesn't support QC currently.
