### ISSUE TITLE
POCO F1 USB HUB HDMI 

### ISSUE THREAD

**Issue by ClouDROID-Dev** [edk2-porting/edk2-sdm845#118]
I want to know if hdmi is working on windows arm on poco using this hub
![image](https://user-images.githubusercontent.com/80438143/165250608-6de9df19-bdea-47de-a4bc-756f06346ae0.png)

Can someone here test the HDMI?

**Comment by BigfootACA** [comment]
it's not possible to work. you need one that supports displaylink

**Comment by ClouDROID-Dev** [comment]
> it's not possible to work. you need one that supports displaylink

I will wait for someone tried the hdmi on POCO F1

**Comment by samzanemesis** [comment]
As stated by Bigfoot you need one that supports Displaylink, the display out alt modes are not configured on the poco hardware

**Comment by alexander-pav** [comment]
Here is my Poco with DiplayLink hub
https://youtu.be/GHwdSv_D25Y

**Comment by AdrianoA3** [comment]
@alexander-pav 1. What are the displaylink brand and model?
2. Does is charge the device?

**Comment by alexander-pav** [comment]
> @alexander-pav 1. What are the displaylink brand and model? 2. Does is charge the device?
2 - No, it doesn't
We need additional OTG adapter with PD port but I don't know will it work with renegate windows or not
