### ISSUE TITLE
sdm845音频有没有办法通过听筒实现？（或者已撤回？）

### ISSUE THREAD

**Issue by paulcbfly** [edk2-porting/edk2-sdm845#125]
mix2s群听说有人用听筒代替声音可以发出声音,使用的是MateBook E 2019的驱动,那个人说需要修改boot,已知问题是容易蓝屏。大佬们之前是不是曾经开发过这个,有没有希望通过这个不是很完美的实现方法用听筒发声。设备图如下。额。好像卖100块钱（或者捐赠）,论坛也看到了
![383870f4c4fed9a3](https://user-images.githubusercontent.com/93072923/169693300-62d86813-f5ef-4677-83cb-44454685b73c.jpg)

**Comment by Idonotkno** [comment]
@paulcbfly 听筒和喇叭都走的是amp功放，因为小米的一些问题，导致它无法工作，所以这两个东西目前都不行，3.5mm的耳机孔和usb-c音频是直通声卡的，这个可以实现，但是mix2s没有耳机孔，至于耳机，买个带dac的不好吗。。。。省事

**Comment by paulcbfly** [comment]
@Idonotkno 好吧。昨天群里面确实有人是100买（捐赠？）了一个人的以听筒当声音的驱动,不知道他们怎么搞的,听说是要修改boot什么的。好像出现蓝屏就在群里面问了,结果被卖驱动的人骂了

**Comment by Idonotkno** [comment]
@paulcbfly 看情况吧，如果不是走的amp，那改一个出来也不难，目前暂时没人测试

**Comment by paulcbfly** [comment]
@Idonotkno 好吧,谢谢大佬,大家等音频过于着急了。再等等😂

**Comment by strongtz** [comment]
目前不支持音频，你看到的几乎100%是假的，即使是听筒也不可能
