### ISSUE TITLE
(POCO F1 64GB KOR(global) VERSON) MEMORY_MANAGEMENT error

### ISSUE THREAD

**Issue by hwanghyunseo** [edk2-porting/edk2-sdm845#127]
### Prerequisites

* [O] Have you read the readme?
* [O] Do you (want to) have your device in the supported list?
* [O] Does the device have a Snapdragon 845 SOC?

### Description

MEMORY_MANAGEMENT error is first windows booting bluescreen.

**Expected behavior:** i input uefi img and devcfg img(poco f1 touchscreen fix). I actually expected the touch to work and to be fine.

**Actual behavior:**  MEMORY_MANAGEMENT error,and not booting. winpe is booting

also i use windows 11 arm version 22000.1

**Comment by TAOcroatia** [comment]
Please use [this](https://github.com/edk2-porting/WOA-Drivers/tree/b61155b70e6c67f42fbb7913b6ea97f275c0d118) and the nt36xxx driver for now
The issue is still being investigated.
