### ISSUE TITLE
Latest version of project does not compile

### ISSUE THREAD

**Issue by jodidas** [edk2-porting/edk2-sdm845#139]
### Prerequisites

- [x] Have you read the readme?
- [x] Do you (want to) have your device in the supported list?
- [x] Does the device have a Snapdragon 845 SOC?

### Description

Environment: Ubuntu 20.04 WSL under Windows 11
The required dependencies have been installed in accordance with the compilation guide, but it still does not compile. The error is either an implicitly defined function or many proprietary structs and definitions such as EFI_STATUS cannot be found. Now I am baffled as to what the root cause of the problem is and have no way of getting around it.
My device is a Xiaomi dipper with SimpleInit enabled by default, but the errors occur mainly here.

![image](https://user-images.githubusercontent.com/110917112/183679805-12f68c4f-af38-44b2-a1ae-4f8ab45de42c.png)
![image](https://user-images.githubusercontent.com/110917112/183684401-b000b736-9af8-463b-af67-0e39cac5d5d6.png)

**Comment by KhanhNguyen9872** [comment]
what device you compile? i compile beryllium and polaris without any error

**Comment by BigfootACA** [comment]
please cleanup your environment and recompile
