### ISSUE TITLE
POCO F1 WIFI and Cellular Network Bug

### ISSUE THREAD

**Issue by ClouDROID-Dev** [edk2-porting/edk2-sdm845#145]
After Installing Windows 11 on Poco f1 WIFI and Cellular Network is not showing on Windows boot how to fix this issue

**Comment by srijansaxena11** [comment]
@ClouDROID-Dev Both work fine on Windows 10. In Windows 11 afaik, WiFi works fine after Windows setup is done but Cellular Network doesn't.
