### ISSUE TITLE
Windows getting activated automatically

### ISSUE THREAD

**Issue by strongtz** [edk2-porting/edk2-sdm845#15]
Currently, Windows booted using edk2-sdm845 will be activated automatically once connected to Internet. It might be due to someone activating using Digital Rights.

This may lead to unexpected legal risks.

To solve the issue, generating a unique SMBIOS UUID at runtime based on device serial number might be needed. EFIChipInfo protocol might be required.

It is currently under investigation by @BigfootACA

**Comment by Vicc2008** [comment]
Hello i have a Motorola One Action and I want Port edk2 UEFI to my Motorola One Action

**Comment by Vicc2008** [comment]
Hello i have a Samsung Galaxy A30 and I want Port edk2 UEFI to my Samsung Galaxy A30

**Comment by ivoszbg** [comment]
This is the same case as windows 10 on armv7 lumias - by default devices under 9 inches get automatically activated (https://www.theverge.com/2014/4/2/5574146/microsoft-making-windows-free-on-devices-with-screens-under-nine)
