### ISSUE TITLE
Windows RT 8.1 in this project

### ISSUE THREAD

**Issue by Vicc2008** [edk2-porting/edk2-sdm845#17]
don't install windows 10 arm64 but install windows RT 8.1 on qualcomm snapdragon 845

**Comment by J0SH1X** [comment]
> don't install windows 10 arm64 but install windows RT 8.1 on qualcomm snapdragon 845

Please stop and finally stop annoying everyone and every dev , just buy a f****** supported phone and st**

**Comment by Vicc2008** [comment]
> > don't install windows 10 arm64 but install windows RT 8.1 on qualcomm snapdragon 845
> 
> Please stop and finally stop annoying everyone and every dev , just buy a f****** supported phone and st**
Windows RT 8.1 is recommended for qualcomm snapdragon 845

**Comment by BigfootACA** [comment]
If you want windows10, you need to install the drivers.
