### ISSUE TITLE
Edk2 port for HTC U12+

### ISSUE THREAD

**Issue by mikerosoft500** [edk2-porting/edk2-sdm845#20]
I want to port edk2 for u12+. It comes with sdm845 but also with infamous s-on. Is it possible to port edk2 uefi on u12+?

**Comment by strongtz** [comment]
@mikerosoft500 check commits such as: 
https://github.com/edk2-porting/edk2-sdm845/commit/f6ff409ce8d83302283f54d0a28275367d736c8a

**Comment by BigfootACA** [comment]
when porting to a new device, you need to provide the device's fdt file, resolution and codename. you can join the group chat for more help.
