### ISSUE TITLE
ZenFone 5z?

### ISSUE THREAD

**Issue by GamesAndroidBR** [edk2-porting/edk2-sdm845#22]
would a Port to ZenFone 5z be possible? I would love to test

**Comment by BigfootACA** [comment]
when porting to a new device, you need to provide the device's fdt file, resolution and codename. you can join the group chat for more help.

**Comment by VAILL666** [comment]
hi Bigfoot can you please share the group chat link ?? 
is it discord? if not share it anyways thanks

**Comment by TheMorc** [comment]
telegram and discord links are in readme.md
