### ISSUE TITLE
add support for oneplus 7

### ISSUE THREAD

**Issue by frans4080** [edk2-porting/edk2-sdm845#23]
fdt file: i couldn't find it

resolution: 1080x2340

codename: guacamoleb

reason: to test if this port on this phone

**Comment by Idonotkno** [comment]
This repo is only 845，
For 8150, please see edk2-sm8150，github.com/edk2-porting/edk2-sm8150

**Comment by frans4080** [comment]
and there are no releases on the github page you gave me the link to.

**Comment by Idonotkno** [comment]
You need to wait for a few days and submit it when I have time.

**Comment by J0SH1X** [comment]
-

**Comment by Idonotkno** [comment]
Or go to tg group to see for yourself

**Comment by BigfootACA** [comment]
this repo only accepts sdm845

**Comment by frans4080** [comment]
oh for christ sakes my phone has a snapdragon 845 processor/cpu.

**Comment by TAOcroatia** [comment]
https://m.gsmarena.com/oneplus_7-9623.php

**Comment by frans4080** [comment]
oh nevermind sorry didn't know.
