### ISSUE TITLE
Edk2 for poco x3 pro 8gb ram

### ISSUE THREAD

**Issue by BIGD15** [edk2-porting/edk2-sdm845#24]
Please add support for this phone

**Comment by TheMorc** [comment]
This is intended for SDM845 devices only.

**Comment by TheMorc** [comment]
but SDM860 seems to be related to 855 so you can look into edk2-porting/edk2-SM8150

**Comment by BIGD15** [comment]
Ok

**Comment by BIGD15** [comment]
I can't find it
