### ISSUE TITLE
Can I add device support to the image myself?

### ISSUE THREAD

**Issue by georgiy0804** [edk2-porting/edk2-sdm845#31]
I have phone numbers "Redmi 4 prime" and "Redmi Note 9 Pro". Is it possible to add them to the system image?In the "Pull request" section, I could not create a question. Does this image also support the simultaneous installation of Windows and android systems?

**Comment by strongtz** [comment]
Only sdm845 (Snapdragon 845) devices are supported

**Comment by BigfootACA** [comment]
this repo only accepts sdm845
