### ISSUE TITLE
Can you try to port windows 11 to Lenovo duet

### ISSUE THREAD

**Issue by zainullahk** [edk2-porting/edk2-sdm845#32]
There is a project called cadimum that ported Linux to Lenovo duet can you try to port windows 11 this would be a deal breaker Because windows 11 is very fast

**Comment by TAOcroatia** [comment]
This project is aimed at SDM845 SoC only

**Comment by zainullahk** [comment]
then where can i request!

**Comment by TheMorc** [comment]
> then where can i request!
> […](#)

only if...
No.
You can't. That thing has a MediaTek shitbox SOC in it, not even a Snapdragon.
