### ISSUE TITLE
Just a question: What is the UFS in google and sony phones?

### ISSUE THREAD

**Issue by cuj** [edk2-porting/edk2-sdm845#36]
Hi, I have read the README.MD file, and I read the following:

> # WARNING
> DO NOT EVER TRY TO PORT IT TO SONY and GOOGLE DEVICES
> YOUR UFS WILL BE WIPED CLEAN!!!

I do not understand the meaning of UFS, so is UFS the system files/data of sony and google devices? is it responsible for booting devices? or is UFS the system files of an additional feature only on google/sony phones? it would be much appreciated if someone can tell me what's the UFS. thanks.

**Comment by strongtz** [comment]
@cuj Google "UFS" pls

**Comment by cuj** [comment]
@strongtz

I googled, and the UFS is like the SSD of the sony/google phone, just to be sure, is that true? Thanks.

**Comment by NXij** [comment]
UFS is the storage chip, mobile SOCs keep everything on them, hence when it gets wiped, it essentially bricks the phone with no ability to boot into any kind of uefi/bootloader/fastboot (which includes the ability of being able to flash anything at all).

There is a basic SDL2 port for Pixel 3XL which had its last commit in 2019 though, it does not seem to wipe the ufs, but afaik it does also not have any way to interface with the on device UFS.

**Comment by cuj** [comment]
@NXij

Thanks for telling me what is UFS.

**Comment by cuj** [comment]
Reopening the issue as I have another question:

If I try to port win10 edk2 to sony or google phone, Will the UFS instantly get wiped, or will Windows 10 boot but after a reboot the device is bricked?

**Comment by strongtz** [comment]
It will get wiped instantly

**Comment by Bezouro** [comment]
@cuj please dont edit your messages, it make dificult to ppl like me to clear the same doubts you had
