### ISSUE TITLE
博主你好，骁龙865有机会适配吗？

### ISSUE THREAD

**Issue by LinJiaTi** [edk2-porting/edk2-sdm845#39]
### Prerequisites

* [ ] Have you read the readme?
* [ ] Do you (want to) have your device in the supported list?
* [ ] Does the device have a Snapdragon 845 SOC?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by TheMorc** [comment]
This repo is only for SDM845. *gosh, someone needs to teach you read..*

This one is for SDM865 https://github.com/edk2-porting/EDK2-SM8250

**Comment by LinJiaTi** [comment]
> 此 repo 仅适用于 SDM845。_天哪，有人需要教你阅读.._
> 
> 这是 SDM865 https://github.com/edk2-porting/EDK2-SM8250

谢谢！这网页ui设计有点不太习惯刚学着看阅读。
