### ISSUE TITLE
Can the UEFI of this project boot WTG devices? 

### ISSUE THREAD

**Issue by huangsijun17** [edk2-porting/edk2-sdm845#40]
### Prerequisites

Xiaomi Mi MIX2S

### Description

[Description of the bug or feature]

**Expected behavior:** Boot a WTG device. 

**Actual behavior:** Can it be achieved? How to do it?

**Comment by strongtz** [comment]
@huangsijun17 iirc qcom drivers have no support for WTG, so it's very likely that you'll get stuck on boot
