### ISSUE TITLE
 can you make a port for poco x3 pro

### ISSUE THREAD

**Issue by kwteen** [edk2-porting/edk2-sdm845#42]
### Prerequisites

* [x] Have you read the readme?
* [x] Do you (want to) have your device in the supported list?
* [ ] Does the device have a Snapdragon 845 SOC?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by TheMorc** [comment]
![image](https://user-images.githubusercontent.com/13377926/126574617-e734115f-967a-409d-88be-87db88392796.png)
SDM860 is a tweaked version of 855 and ***this is a SDM845 repo***.
The 855 repo is not available right now on GitHub.

**Comment by strongtz** [comment]
@kwteen Does the device have a Snapdragon 845 SOC?

**Comment by BigfootACA** [comment]
this repo only accepts sdm845

**Comment by proganime1200** [comment]
There is a working uefi kernel for x3 pro on 4pda https://4pda.to/forum/index.php?showtopic=884586&st=2340
