### ISSUE TITLE
Question:Support for "OPPO Reno A".

### ISSUE THREAD

**Issue by creeper-0910** [edk2-porting/edk2-sdm845#45]
"OPPO Reno A" is equipped with Snapdragon 845, but it is not supported.
Do you plan to support it?

**Comment by TheMorc** [comment]
We don't have the devices so if you're willing to, you can port it

**Comment by Idonotkno** [comment]
@creeper-0910 Findx and oneplus have been tested, and other OPPO devices can work in theory, but you need to test your own functions

**Comment by creeper-0910** [comment]
> 私たちはデバイスを持っていないので、あなたが喜んでそれを移植することができます
> 
> https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417

Do I need root privileges on my device to run this?

**Comment by BigfootACA** [comment]
> > 私たちはデバイスを持っていないので、あなたが喜んでそれを移植することができます
> > https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417
> 
> Do I need root privileges on my device to run this?

the bootloader must be unlocked

**Comment by creeper-0910** [comment]
I'm sorry.
It seems that SDM710 was displayed as 845 due to a bug(?) in CPU-Z...
Oppo reno A is not SDM845...
