### ISSUE TITLE
oneplus 6 touch screen stop working after lock screen and hold touch right click menu not function

### ISSUE THREAD

**Issue by niuniu132** [edk2-porting/edk2-sdm845#48]
### Prerequisites

* [x] Have you read the readme?
* [x] Do you (want to) have your device in the supported list?
* [x] Does the device have a Snapdragon 845 SOC?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by strongtz** [comment]
@niuniu132 That's expected.
Also, please use English.

**Comment by cruisermaxx** [comment]
I also find the touch screen stop problem. Could this be fixed on oneplus 6/6t?

**Comment by TheMorc** [comment]
We know about the current issues
https://forum.renegade-project.org/t/current-synaptics-touch-driver-issues/204

**Comment by TheMorc** [comment]
> I also find the touch screen stop problem. Could this be fixed on oneplus 6/6t?

The "touchscreen stop" problem has been fixed for now. It shouldn't happen now with the latest drivers but you'll still have issues with right clicking.

**Comment by TheMorc** [comment]
@cruisermaxx @niuniu132

Try the latest driver from WOA-Drivers, it should work now on your replaced screen with a counterfeit digitizer controller IC.

**Comment by TAOcroatia** [comment]
Issue already open on different repo
