### ISSUE TITLE
NX616J bluescreen error

### ISSUE THREAD

**Issue by oniyakun** [edk2-porting/edk2-sdm845#54]
### Prerequisites

* [ ] Have you read the readme? 
yes
* [ ] Do you (want to) have your device in the supported list? 
yes
* [ ] Does the device have a Snapdragon 845 SOC? 
yes

### Description

[Description of the bug or feature]

I followed the tutorial through all the steps, now using the uefi from Ci did fixed USB issue but within bluescreen 'Soc Subsystem Failure', there is any chance to get it work?

**Expected behavior:** [What you expected to happen]

Boot in Windows

**Actual behavior:** [What actually happened]

Bluescreen with error code 'Soc Subsystem Failure'

**Comment by ClouDROID-Dev** [comment]
Uninstall Audio drivers i fixed on POCO F1
