### ISSUE TITLE
联发科天玑800u没希望了吗，我的红米note9 5g吃灰了

### ISSUE THREAD

**Issue by cqy20091031mc** [edk2-porting/edk2-sdm845#60]
### Prerequisites

* [ ] Have you read the readme?
* [ ] Do you (want to) have your device in the supported list?
* [ ] Does the device have a Snapdragon 845 SOC?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BigfootACA** [comment]
联发科没有适配计划，并且该仓库仅适配骁龙845
[常见问题收集 ](https://forum.renegade-project.org/t/topic/62)

**Comment by cqy20091031mc** [comment]
骁龙855是不是也有希望

**Comment by strongtz** [comment]
@cqy20091031mc Sunflower2333：洗洗睡

**Comment by cqy20091031mc** [comment]
哎，没希望了

**Comment by cqy20091031mc** [comment]
跑了10家手机店，2座电脑城都没找到845的

**Comment by cqy20091031mc** [comment]
用模拟器的转换效率太低了

**Comment by cqy20091031mc** [comment]
所以，只有，把845所有适配好，才能适配其他的吗
