### ISSUE TITLE
Is it possible to add new resolution for mix2s or other devices

### ISSUE THREAD

**Issue by luojunyuan** [edk2-porting/edk2-sdm845#63]
### Prerequisites

* [x] Have you read the readme?
* [x] Do you (want to) have your device in the supported list?
* [x] Does the device have a Snapdragon 845 SOC?

### Description

Currently resolution in Setting-Display, can be only setting to 2160*1080. Can It be changed to other resolution like 1280 * 720 ? It's really useful.

**Expected behavior:** More resoulution or DPI scaling can be used.

**Actual behavior:** 2160*1080 and DPI 100% to 175%

**Comment by JeromTWinL** [comment]
Go to Settings->Display->Scaling->change scaling from '100% (Recommended)' to '125%', you'll see the changes with low resolution
