### ISSUE TITLE
MIX2S偶尔会掉WiFi或无法联网

### ISSUE THREAD

**Issue by shallowdream-over** [edk2-porting/edk2-sdm845#67]
### Prerequisites

* [x] Have you read the readme?
* [x] Do you (want to) have your device in the supported list?
* [x] Does the device have a Snapdragon 845 SOC?

### Description

[偶尔会掉WiFi或无法联网]

**预期行为:** [正常联网]

**实际行为:** [刚开机或者锁屏后再打开，会看到wifi已连接但仍然无法联网的情况(WiFi提示无法连接Internet)，要等待两分钟才能联网。
有时还会出现等着等着wifi模块不见的情况(出现3-4次了)，还有的时候正常使用用着用着wifi模块也消失了(只出现过一次)，设置里找不到wifi选项卡，设备管理器查看发现WiFi驱动感叹号，该设备无法启动(错误代码10，请求的操作不成功)，重启可以解决]

**设备描述:** [MIX2S 6+64 windows版本：win11 InsiderPreview 22468.1000]

**Comment by DinnerABC** [comment]
我的魅族16Plus也有wifi模块直接消失的问题，且经常发生。在设备管理器中重新设置驱动也不好使。目前不知道什么情况会消失，什么情况会正常。

**Comment by kvinwang** [comment]
最近似乎比较稳定了，不知道是不是因为点了windows更新后修复了。

**Comment by strongtz** [comment]
如果没有问题的话，我就把issue close了

**Comment by Idonotkno** [comment]
@strongtz 更换固件
