### ISSUE TITLE
MIX2S关机问题

### ISSUE THREAD

**Issue by shallowdream-over** [edk2-porting/edk2-sdm845#68]
### Prerequisites

* [x] Have you read the readme?
* [x] Do you (want to) have your device in the supported list?
* [x] Does the device have a Snapdragon 845 SOC?

### Description

[MIX2S关机\重启问题]

**预期行为:** [正常关机，关机充电不自动开机]

**实际行为:** [关机黑屏后几分钟设备都是无响应的状态，重启也是差不多要等待好几分钟才能启动，除非长按10s强制重启。

关机状态下连接充电器会自动开机，希望能调用原系统充电动画]

**设备描述:** [MIX2S 6+64 windows版本：win11 InsiderPreview 22468.1000]

**Comment by justicewang949** [comment]
meizu 16th plus同样的问题，关机后只是黑屏不能正常关机，，强制重启后开机会大几率失败进入修复引导，再次重启才会有一定几率开机成功

**Comment by strongtz** [comment]
这个是固件问题，我们可能无法解决
This is a firmware issue. We might not be able to fix it.
