### ISSUE TITLE
usb视频输出 接hdmi线

### ISSUE THREAD

**Issue by YYJavaGit** [edk2-porting/edk2-sdm845#69]
我手里有个小米8 刷win11不是没有触屏嘛 显示屏又太小 我想接个hdmi到显示器用 我上次拿绿联的转接口试了一下貌似不行

**Comment by strongtz** [comment]
@YYJavaGit 小米8硬件不支持type-c displayport alt-mode，你只能在淘宝上购买支持DisplayLink的扩展坞或转接头

**Comment by strongtz** [comment]
@YYJavaGit 目前均不支持DP直接输出

**Comment by YYJavaGit** [comment]
好吧 谢谢 taobao有卖那种屏幕视频线转hdmi的吗 这条路走不通不想diy一下
