### ISSUE TITLE
UEFI固件修改的设置无法保存

### ISSUE THREAD

**Issue by huangsijun17** [edk2-porting/edk2-sdm845#80]
### Prerequisites

* [X] Have you read the readme?
* [X] Do you (want to) have your device in the supported list?
* [X] Does the device have a Snapdragon 845 SOC?

### Description

我在UEFI固件中修改了引导顺序的设置。

**Expected behavior:** 重启后设置被复原。

**Actual behavior:** 重启后设置保留。

**Comment by strongtz** [comment]
This problem cannot get solved in a easy way. Maybe try modifying simpleinit configuration for your use case.
