### ISSUE TITLE
Sdm860

### ISSUE THREAD

**Issue by romario056** [edk2-porting/edk2-sdm845#81]
Hello, can I here contact with  dev's with a question?
i want to be a tester! I have redmi k20 (730) and xiaomi pad 5 (860). Can you tell me, why did you del rep. edk2-sm7150 and edk2-msmnile? May be you want to work on it, or it was due to the impossibility of project? As i know, for device on sdm860 its possible)) 
Sorry for taking your time, but i cant how can i contact with you other. 
Tx for understanding!

**Comment by BigfootACA** [comment]
this repo only accepts sdm845
