### ISSUE TITLE
poco f1 windows 11 charge not working

### ISSUE THREAD

**Issue by hwanghyunseo** [edk2-porting/edk2-sdm845#86]
### Prerequisites

* [ok] Have you read the readme?
* [ok] Do you (want to) have your device in the supported list?
* [ok] Does the device have a Snapdragon 845 SOC?

### Description

poco f1 is charge not working

**Expected behavior:** 
I was told it was charging.

**Actual behavior:**
poco f1 is charge on windows 11 arm not working

**Comment by Aro2142** [comment]
What kind of power supply do you have?  
Maybe you have a problem with the connector.  (My poco is charging when I insert the charging wire with a seam to the screen)

**Comment by hwanghyunseo** [comment]
I switched to the default charger and it is charging.
