### ISSUE TITLE
求适配LG v40也就是judypn，使用LG G7的efi无法启动

### ISSUE THREAD

**Issue by zmnsQ** [edk2-porting/edk2-sdm845#87]
求适配LG v40也就是judypn，使用LG G7的efi无法启动

**Comment by Idonotkno** [comment]
@zmnsQ Use your device dtb

**Comment by KlNGDRAGON** [comment]
@Idonotkno I have generated dtb files of LG V40 according to the official kernel, but many dtb files have been generated which one should I use
