### ISSUE TITLE
Clarification: UFS wipe

### ISSUE THREAD

**Issue by IngwiePhoenix** [edk2-porting/edk2-sdm845#88]
### Prerequisites

* [x] Have you read the readme?
* [ ] Do you (want to) have your device in the supported list?
* [ ] Does the device have a Snapdragon 845 SOC?

### Description

In the README, it is stated to never port to Sony or Google devices due to the UFS being wiped. Why, exactly? I am curious and would like to know :)

**Expected behavior:**

Not a whole lot; just a little bit of clarification. I know what a UFS is - just not why it becomes wiped when trying to run this port.

**Actual behavior:**

Curiosity I guess?

Kind regards,
Ingwie

**Comment by Idonotkno** [comment]
@IngwiePhoenix OTP

**Comment by luka177** [comment]
@IngwiePhoenix Actually on pixel devices it is wiped not by uefi but by windows driver, so probably you can boot mainline

**Comment by Idonotkno** [comment]
@luka177 It triggers the protection of ufs itself, which is the same on the main line. It can only be used if the ufs driver for sony is modified.

**Comment by luka177** [comment]
@Idonotkno On Sony probably, while on pixel mainline is confirmed working with ufs, https://wiki.postmarketos.org/wiki/Google_Pixel_3(google-blueline)

**Comment by IngwiePhoenix** [comment]
> @IngwiePhoenix OTP

Trying to google that leads me to a lot of "One Time Password" related apps. You likely don't mean that one, do you?

**Comment by Idonotkno** [comment]
@luka177 Unfortunately, we don't have the ufs driver source code for Windows, so we can't customize it.

**Comment by Idonotkno** [comment]
@IngwiePhoenix Ufs protection is turned on.

**Comment by Idonotkno** [comment]
@Idonotkno See the following questions completely.
