### ISSUE TITLE
please make this to run on sd870

### ISSUE THREAD

**Issue by hardrisk27dn** [edk2-porting/edk2-sdm845#89]
### Prerequisites

* [ ] Have you read the readme?
* [ ] Do you (want to) have your device in the supported list?
* [ ] Does the device have a Snapdragon 845 SOC?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BigfootACA** [comment]
this repo only accepts sdm845
