### ISSUE TITLE
求适配pixel3 （blueline）

### ISSUE THREAD

**Issue by EnderKi** [edk2-porting/edk2-sdm845#90]
### Prerequisites

* [√ ] Have you read the readme?
* [ √ ] Do you (want to) have your device in the supported list?
* [ √ ] Does the device have a Snapdragon 845 SOC?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by Idonotkno** [comment]
@EnderKi Unless your device is prototype.Otherwise, don't try Windows

**Comment by EnderKi** [comment]
> 
It is prototype

**Comment by EnderKi** [comment]
> @EnderKi Unless your device is prototype.Otherwise, don't try Windows

I want try it.

**Comment by Idonotkno** [comment]
@EnderKi Follow the relevant links to enter the group.

**Comment by EnderKi** [comment]
> @EnderKi Follow the relevant links to enter the group.

where can i find the group

**Comment by Idonotkno** [comment]
@EnderKi I don't know.

**Comment by BigfootACA** [comment]
https://forum.renegade-project.org/t/group-chat/68
