### ISSUE TITLE
driver for razerphone 2

### ISSUE THREAD

**Issue by whynot4444** [edk2-porting/edk2-sdm845#93]
Hello i have a razer phone 2, can i using driver and boot from one plus 6T ?, or i can try it

**Comment by BigfootACA** [comment]
https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417

**Comment by whynot4444** [comment]
> https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417

thanks you, and WOA Driver can do like this ?

**Comment by whynot4444** [comment]
> https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417

ok im try to complie, but it show unknow error, this razer phone 2 have 2 boot a and b, this tutorial can work ?

**Comment by BigfootACA** [comment]
> > https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417
> 
> thanks you, and WOA Driver can do like this ?

based on sdm845-generic

**Comment by whynot4444** [comment]
> > > https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417
> > 
> > 
> > ok im try to complie, but it show unknow error, this razer phone 2 have 2 boot a and b, this tutorial can work ?
> 
> yes

im try it show unknow error

**Comment by whynot4444** [comment]
> > > https://forum.renegade-project.org/t/edk2-sdm845-new-device-porting-guide/417
> > 
> > 
> > ok im try to complie, but it show unknow error, this razer phone 2 have 2 boot a and b, this tutorial can work ?
> 
> yes

flash ok but hang logo, haizza

**Comment by Idonotkno** [comment]
@whynot4444 Replace dtb, define resolution

**Comment by whynot4444** [comment]
> @whynot4444 Replace dtb, define resolution

it only 1 dtb, resolution have 2 is 2K and fullhd, im choosing fullHD

**Comment by Idonotkno** [comment]
@whynot4444 Replace common dtb and configuration, and compile common models.

**Comment by whynot4444** [comment]
> @whynot4444 Replace common dtb and configuration, and compile common models.

ah you have tutorial of this, because this is first time im using linux

**Comment by Idonotkno** [comment]
@whynot4444 Join the group

**Comment by whynot4444** [comment]
> @whynot4444 Join the group

im on discord now
