### ISSUE TITLE
Question: that can run on samsung galaxy a12 (sm-a127f)?

### ISSUE THREAD

**Issue by moha0116** [edk2-porting/edk2-sdm845#94]
### Prerequisites

* [ ] Have you read the readme?
* [ ] Do you (want to) have your device in the supported list?
* [ ] Does the device have a Snapdragon 845 SOC?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BigfootACA** [comment]
this repo only accepts sdm845
