### ISSUE TITLE
Can I install windows 11 on the samsung galaxy s8

### ISSUE THREAD

**Issue by markok16310** [edk2-porting/edk2-sdm845#96]
Does this project support the samsung galaxy s8 and is it compatible with snapdragon 835 processors in general? If it is, did anyone manage to install windows 11 on the s8?

**Comment by curoviyxru** [comment]
Refer to https://renegade-project.org/#/en/windows/state-frame.html. Some of MSM8998 (SDM835) devices are supported, but Samsung Galaxy S8 not.

**Comment by markok16310** [comment]
> Refer to https://renegade-project.org/#/en/windows/state-frame.html. Some of MSM8998 (SDM835) devices are supported, but Samsung Galaxy S8 not.

What phone on the list of devices supported is the most compatible with windows 11?

**Comment by strongtz** [comment]
Look at the top of the list
